// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Serendipity565/GrabSeat/config"
	"github.com/Serendipity565/GrabSeat/controller"
	"github.com/Serendipity565/GrabSeat/middleware"
	"github.com/Serendipity565/GrabSeat/pkg/ijwt"
	"github.com/Serendipity565/GrabSeat/pkg/logger"
	"github.com/Serendipity565/GrabSeat/service"
)

// Injectors from wire.go:

func InitApp() *App {
	jwtConfig := config.NewJWTConfig()
	jwt := ijwt.NewJWT(jwtConfig)
	loginService := service.NewLoginService()
	loginController := controller.NewLoginController(jwt, loginService)
	garbController := controller.NewGarbHandler()
	middlewareConfig := config.NewMiddlewareConfig()
	corsMiddleware := middleware.NewCorsMiddleware(middlewareConfig)
	authMiddleware := middleware.NewAuthMiddleware(jwt)
	zapLogger := logger.NewZapLogger()
	loggerMiddleware := middleware.NewLoggerMiddleware(zapLogger)
	engine := controller.NewGinEngine(loginController, garbController, corsMiddleware, authMiddleware, loggerMiddleware)
	ticker := service.NewTicker()
	app := &App{
		r: engine,
		t: ticker,
	}
	return app
}
