// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Serendipity565/GrabSeat/config"
	"github.com/Serendipity565/GrabSeat/controller"
	"github.com/Serendipity565/GrabSeat/ioc"
	"github.com/Serendipity565/GrabSeat/middleware"
	"github.com/Serendipity565/GrabSeat/pkg/ijwt"
	"github.com/Serendipity565/GrabSeat/pkg/logger"
	"github.com/Serendipity565/GrabSeat/service"
)

// Injectors from wire.go:

func InitApp() *App {
	healthCheckService := service.NewHealthCheckService()
	healthCheckController := controller.NewHealthCheckController(healthCheckService)
	jwtConfig := config.NewJWTConfig()
	jwt := ijwt.NewJWT(jwtConfig)
	loginService := service.NewLoginService()
	loginController := controller.NewLoginController(jwt, loginService)
	logConfig := config.NewLogConfig()
	zapLogger := ioc.InitLogger(logConfig)
	loggerLogger := logger.NewZapLogger(zapLogger)
	grabberService := service.NewGrabberService(loggerLogger)
	garbController := controller.NewGarbHandler(grabberService)
	middlewareConfig := config.NewMiddlewareConfig()
	corsMiddleware := middleware.NewCorsMiddleware(middlewareConfig)
	authMiddleware := middleware.NewAuthMiddleware(jwt)
	v := config.NewBasicAuthConfig()
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware(v)
	loggerMiddleware := middleware.NewLoggerMiddleware(loggerLogger)
	limiterConfig := config.NewLimiterConfig()
	redisConfig := config.NewRedisConfig()
	cmdable := ioc.InitRedis(redisConfig)
	limitMiddleware := middleware.NewLimitMiddleware(limiterConfig, cmdable)
	registry := ioc.InitPrometheus()
	prometheusMiddleware := middleware.NewPrometheusMiddleware(registry)
	engine := controller.NewGinEngine(healthCheckController, loginController, garbController, corsMiddleware, authMiddleware, basicAuthMiddleware, loggerMiddleware, limitMiddleware, prometheusMiddleware)
	ticker := service.NewTicker()
	app := &App{
		r: engine,
		t: ticker,
	}
	return app
}
