// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Serendipity565/GrabSeat/service (interfaces: LoginService)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoginService is a mock of LoginService interface.
type MockLoginService struct {
	ctrl     *gomock.Controller
	recorder *MockLoginServiceMockRecorder
}

// MockLoginServiceMockRecorder is the mock recorder for MockLoginService.
type MockLoginServiceMockRecorder struct {
	mock *MockLoginService
}

// NewMockLoginService creates a new mock instance.
func NewMockLoginService(ctrl *gomock.Controller) *MockLoginService {
	mock := &MockLoginService{ctrl: ctrl}
	mock.recorder = &MockLoginServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginService) EXPECT() *MockLoginServiceMockRecorder {
	return m.recorder
}

// Login2CAS mocks base method.
func (m *MockLoginService) Login2CAS(arg0, arg1 string) (*http.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login2CAS", arg0, arg1)
	ret0, _ := ret[0].(*http.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login2CAS indicates an expected call of Login2CAS.
func (mr *MockLoginServiceMockRecorder) Login2CAS(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login2CAS", reflect.TypeOf((*MockLoginService)(nil).Login2CAS), arg0, arg1)
}
