// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ccnu/login": {
            "post": {
                "description": "用户登录，返回 JWT 令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 JWT 令牌",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/garb/findvacantseats": {
            "post": {
                "description": "查找空座位接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "garb"
                ],
                "summary": "查找空座位接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {{JWT}}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查找空座位请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FindVacantSeatsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回空座位列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.Seat"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/garb/garb": {
            "post": {
                "description": "抢座接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "garb"
                ],
                "summary": "抢座接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {{JWT}}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "抢座请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GarbReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回抢座结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/garb/isinlibrary": {
            "post": {
                "description": "检查目标用户当前是否在图书馆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "garb"
                ],
                "summary": "检查目标用户当前是否在图书馆",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {{JWT}}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "检查目标用户当前是否在图书馆请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.IsInLibraryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回在图书馆的时间段",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/garb/seatttoname": {
            "post": {
                "description": "座位号转名字接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "garb"
                ],
                "summary": "座位号转名字接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {{JWT}}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "座位号转名字请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SeatToNameReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回座位号对应的名字",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.Ts"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "健康检查，返回当前服务占用的资源等信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查，返回当前服务占用的资源等信息",
                "responses": {
                    "200": {
                        "description": "成功返回健康检查结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.HealthCheckResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.FindVacantSeatsReq": {
            "type": "object",
            "required": [
                "end_time",
                "is_tomorrow",
                "start_time"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "is_tomorrow": {
                    "type": "boolean"
                },
                "key_word": {
                    "description": "可选参数，模糊搜索关键词",
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "request.GarbReq": {
            "type": "object",
            "required": [
                "end_time",
                "is_tomorrow",
                "start_time"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "is_tomorrow": {
                    "type": "boolean"
                },
                "seat_id": {
                    "description": "可选参数,指定座位ID,不指定则自动选择",
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "request.IsInLibraryReq": {
            "type": "object",
            "required": [
                "student_name"
            ],
            "properties": {
                "student_name": {
                    "description": "学生姓名",
                    "type": "string"
                }
            }
        },
        "request.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.SeatToNameReq": {
            "type": "object",
            "required": [
                "is_tomorrow",
                "seat_name"
            ],
            "properties": {
                "is_tomorrow": {
                    "type": "boolean"
                },
                "seat_name": {
                    "description": "座位名称,例如 N1224",
                    "type": "string"
                }
            }
        },
        "response.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "process": {
                    "description": "Process 当前进程的运行状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.ProcessStats"
                        }
                    ]
                },
                "response_ms": {
                    "description": "ResponseMs 响应耗时，单位毫秒",
                    "type": "string"
                },
                "status": {
                    "description": "Status 服务状态，例如 \"ok\"",
                    "type": "string"
                },
                "system": {
                    "description": "System 系统资源使用情况",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.SystemStats"
                        }
                    ]
                }
            }
        },
        "response.ProcessStats": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "description": "CPUPercent 进程 CPU 使用率（%）",
                    "type": "string"
                },
                "go_heap_alloc_mb": {
                    "description": "GoHeapAllocMB Go 堆分配的内存（MB）",
                    "type": "string"
                },
                "goroutines": {
                    "description": "Goroutines 当前运行的 goroutine 数",
                    "type": "string"
                },
                "memory_rss_mb": {
                    "description": "MemoryRSSMB 进程常驻内存（MB）",
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "response.Seat": {
            "type": "object",
            "properties": {
                "devId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "ts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Ts"
                    }
                }
            }
        },
        "response.SystemStats": {
            "type": "object",
            "properties": {
                "cpu_percent": {
                    "description": "CPUPercent CPU 使用率（%）",
                    "type": "string"
                },
                "disk_percent": {
                    "description": "DiskPercent 磁盘使用率（%）",
                    "type": "string"
                },
                "disk_total": {
                    "description": "DiskTotalGB 磁盘总量（GB）",
                    "type": "string"
                },
                "disk_used": {
                    "description": "DiskUsedGB 已使用磁盘（GB）",
                    "type": "string"
                },
                "memory_percent": {
                    "description": "MemoryPercent 内存使用率（%）",
                    "type": "string"
                },
                "memory_total": {
                    "description": "MemoryTotalMB 内存总量（MB）",
                    "type": "string"
                },
                "memory_used": {
                    "description": "MemoryUsedMB 已使用内存（MB）",
                    "type": "string"
                }
            }
        },
        "response.Ts": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
